[package]
name = "rustapi"
version = "0.1.0"
authors = ["ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.10.1"
log = "0.4.11"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
serde_derive = "1.0.116"
actix-web = "3.1.0"
actix-cors = "0.5.0"
wither = "0.9.0-alpha.2"
futures = "0.3.6"
thiserror = "1.0.21"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = [
  "run-for-all",
  "prepush-hook",
  "precommit-hook",
  "run-cargo-check",
  "run-cargo-clippy",
  "run-cargo-fmt",
  "run-cargo-test",
]