[package]
name = "rustapi"
version = "0.1.0"
authors = ["ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2021"

[dependencies]
config = "0.11.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
serde_derive = "1.0.133"
wither = "0.9.0"
futures = "0.3.19"
thiserror = "1.0.30"
axum = "0.4.4"
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.6"
tower-http = { version = "0.2.0", features = ["trace", "compression-br", "propagate-header", "sensitive-headers"] }
http = "0.2.6"
chrono = "0.4.19"
async-trait = "0.1.52"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = [
  "precommit-hook",
  "run-cargo-check",
  "run-cargo-clippy",
  "run-cargo-fmt",
  "run-cargo-test",
]
